/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Persistencia.*;
import Entidades.*;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucio
 */
public class AsientosV extends javax.swing.JInternalFrame {
    
  private DefaultTableModel modelo = new DefaultTableModel();
    

    /**
     * Creates new form Asientos
     */
    public AsientosV() {
        initComponents();
        cabecera();
        cargarComboP();
        cargarCombosS();
        limpiar();
        configurarColores ();
        /*
        jcbProyeccion.setSelectedIndex(-1);
        jcbSalas.setSelectedIndex(-1);
        jcbFilas.setSelectedIndex(-1);
        jcbNumero.setSelectedIndex(-1);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbFilas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcbNumero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbProyeccion = new javax.swing.JComboBox<>();
        jcbSalas = new javax.swing.JComboBox<>();
        jbOcupar = new javax.swing.JButton();
        jbLiberar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAsientos = new javax.swing.JTable();
        jbMostrar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbGenerar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asiento");

        jLabel2.setText("Fila:");

        jcbFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFilasActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero:");

        jLabel4.setText("Proyeccion:");

        jLabel5.setText("Sala:");

        jcbProyeccion.setToolTipText("");
        jcbProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProyeccionActionPerformed(evt);
            }
        });

        jcbSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSalasActionPerformed(evt);
            }
        });

        jbOcupar.setText("Ocupar");
        jbOcupar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOcuparActionPerformed(evt);
            }
        });

        jbLiberar.setText("Liberar");
        jbLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLiberarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jtAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtAsientos);

        jbMostrar.setText("Mostrar");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGenerar.setText("Generear");
        jbGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbOcupar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbLiberar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbFilas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSalas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbNumero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGenerar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOcupar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLiberar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar))
                .addGap(18, 18, 18)
                .addComponent(jbBuscar)
                .addGap(18, 18, 18)
                .addComponent(jbMostrar)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jcbProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProyeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbProyeccionActionPerformed

    private void jbGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarActionPerformed
       // TODO add your handling code here:
       Sala salaS = (Sala) jcbSalas.getSelectedItem();
       Proyeccion proyS = (Proyeccion) jcbProyeccion.getSelectedItem();
        
        if (salaS == null || proyS == null) {
            
            JOptionPane.showMessageDialog(this, "Es necesario eligir Sala para Acceder a esta opcion.");
            return;
            
        } else {
            
            generarAsiento();
        }
        
        limpiar();
    }//GEN-LAST:event_jbGenerarActionPerformed

    private void jcbFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFilasActionPerformed
        // TODO add your handling code here:
   
        Sala salaSel = (Sala) jcbSalas.getSelectedItem();
        String filaSel = (String) jcbFilas.getSelectedItem();
        
        if (salaSel != null && filaSel != null) {
            
            cargarNumerosPorFilas ();
        }
    }//GEN-LAST:event_jcbFilasActionPerformed

    private void jcbSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSalasActionPerformed
        // TODO add your handling code here:
         
        Sala salaSeleccionado = (Sala) jcbSalas.getSelectedItem();
        
        if (salaSeleccionado != null) {
            
            cargarFilas ();
        }
         
    }//GEN-LAST:event_jcbSalasActionPerformed

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        // TODO add your handling code here:
        mostrarAsientosXSalas();
        jcbProyeccion.setSelectedIndex(-1);
        jcbSalas.setSelectedIndex(-1);
        jcbFilas.setSelectedIndex(-1);
        jcbNumero.setSelectedIndex(-1);
    }//GEN-LAST:event_jbMostrarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        
        if (salaS == null) {
            
            JOptionPane.showMessageDialog(this, "Es necesario eligir Sala para Acceder a esta opcion.");
            return;
            
        } else {
            
            eliminarAsientos();
        }
        
        limpiar ();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        String filaS = (String) jcbFilas.getSelectedItem();
        String numeroS = (String) jcbNumero.getSelectedItem();
        
        if (salaS == null || filaS == null || numeroS == null ) {
            
            JOptionPane.showMessageDialog(this, "Es necesario eligir Sala, Fila y Numero para Acceder a esta opcion.");
            return;
            
        } else {
            
            buscarAsiento ();
        }
        limpiar ();

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbOcuparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOcuparActionPerformed
        // TODO add your handling code here:
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        String filaS = (String) jcbFilas.getSelectedItem();
        String numeroS = (String) jcbNumero.getSelectedItem();
        
        if (salaS == null || filaS == null || numeroS == null ) {
            
            JOptionPane.showMessageDialog(this, "Es necesario eligir Sala, Fila y Numero para Acceder a esta opcion.");
            return;
            
        } else {
            
            ocupar();
        }
        
        limpiar ();
    }//GEN-LAST:event_jbOcuparActionPerformed

    private void jbLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLiberarActionPerformed
        // TODO add your handling code here:
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        String filaS = (String) jcbFilas.getSelectedItem();
        String numeroS = (String) jcbNumero.getSelectedItem();
        
        if (salaS == null || filaS == null || numeroS == null ) {
            
            JOptionPane.showMessageDialog(this, "Es necesario eligir Sala, Fila y Numero para Acceder a esta opcion.");
            return;
            
        } else {
         
            liberar();
        }
        
        limpiar ();
    }//GEN-LAST:event_jbLiberarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGenerar;
    private javax.swing.JButton jbLiberar;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JButton jbOcupar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcbFilas;
    private javax.swing.JComboBox<String> jcbNumero;
    private javax.swing.JComboBox<Object> jcbProyeccion;
    private javax.swing.JComboBox<Object> jcbSalas;
    private javax.swing.JTable jtAsientos;
    // End of variables declaration//GEN-END:variables

    private void generarAsiento(){
        
        AsientoData ad = new AsientoData();
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        
        if (ad.existeAsiento(salaS.getIdSala()) && proy != null) {
            
            JOptionPane.showMessageDialog(this, "Esta sala ya tiene asientos. No se pueden generar si hay asientos. ");
        } else {
            
            ad.generarAsientos(salaS, proy);
        }
    }
    
    private void mostrarAsientosXSalas(){
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        AsientoData ad = new AsientoData();
        
        if (salaS == null) {
            
            JOptionPane.showMessageDialog(this, "Debe eligir una sala.");
            return;
        }
        
        modelo.setRowCount(0);
        
        List<Asiento> lista = ad.listarAsientos(salaS.getIdSala());
        
        for (Asiento a : lista) {
            
            String estado = "";
            
            if (a.isDisponible() == true) {
                
                estado = "Disponible";
            } else {
                
                estado = "Ocupado";
            }
            
            modelo.addRow(new Object []{
                a.getProy().getIdProyeccion() ,
                a.getSala().getNroSala() , 
                a.getFila() ,
                a.getNúmero() ,
                estado    
            });
        }
    }
    
    private void eliminarAsientos(){
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        
        AsientoData ad = new AsientoData();

        
        if (salaS == null) {
            
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una Sala");
            return;
        } else {
        
            int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar todos los asientos de la sala " + salaS.getNroSala() + " ?", "Confirma eliminacion", JOptionPane.YES_NO_OPTION);
        
            if (confirm == JOptionPane.YES_OPTION) {
            
                ad.borrarAsientoPorSala(salaS.getIdSala());
            }
        }
        
        jcbNumero.removeAllItems();
        jcbFilas.removeAllItems();
    }
    
    private void buscarAsiento (){
        
        modelo.setRowCount(0);
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        String fila = (String) jcbFilas.getSelectedItem();
        String numeroStr = ((String) jcbNumero.getSelectedItem()).split(" ")[0];
        int numero = Integer.parseInt(numeroStr);
        
        AsientoData ad = new AsientoData();
        
        Asiento asiento = ad.buscarAsiento(salaS.getIdSala(), fila, numero);
        
        if ( asiento != null) {
            
            String estado = "";
            
            if (asiento.isDisponible() == true) {
                
                estado = "Disponible";
            } else {
                
                estado = "Ocupado";
            }
            
            modelo.addRow(new Object []{
                
                asiento.getProy().getIdProyeccion(),
                asiento.getSala().getNroSala(),
                asiento.getFila(), 
                asiento.getNúmero(),
                estado
            });
        } else {
            
            JOptionPane.showMessageDialog(this, "No se encontro ningun asiento.");
        }
    }
    
    private void ocupar(){
        
        AsientoData ad = new AsientoData();
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        String fila = (String) jcbFilas.getSelectedItem();
        String texto = jcbNumero.getSelectedItem().toString();
        String numeroStr = texto.split(" ")[0];
        Integer numero = Integer.parseInt(numeroStr);
        
        if (salaS == null || fila == null || numero == null ) {
            
            JOptionPane.showMessageDialog(this, "Debe seleccionar sala, fila y numero");
            return;
        }
        
       Asiento asiento = ad.buscarAsiento(salaS.getIdSala(), fila, numero);
        
        if (asiento != null) {
            
            ad.ocuparAsiento(asiento.getIdAsiento());
            JOptionPane.showMessageDialog(this, "Asiento Ocupado Correctamente.");
        } else {
            
            JOptionPane.showMessageDialog(this, "No se Encotro el asiento indicado");
        }
        
        mostrarAsientosXSalas();
    }
    
    private void liberar(){
        
        AsientoData ad = new AsientoData();
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        String fila = (String) jcbFilas.getSelectedItem();
        String texto = jcbNumero.getSelectedItem().toString();
        String numeroStr = texto.split(" ")[0];
        Integer numero = Integer.parseInt(numeroStr);
        
        if (salaS == null || fila == null || numero == null ) {
            
            JOptionPane.showMessageDialog(this, "Debe seleccionar sala, fila y numero");
            return;
        }
        
        Asiento asiento = ad.buscarAsiento(salaS.getIdSala(), fila, numero);
        
        if (asiento != null) {
            
            ad.liberarAsiento(asiento.getIdAsiento());
            JOptionPane.showMessageDialog(this, "Asiento Liberado Correctamente");
        } else {
            
            JOptionPane.showMessageDialog(this, "No se Encotro el asiento indicado");

        }
        
        mostrarAsientosXSalas();
    }
   //------------ Vistas ------------
    
    private void cargarComboP(){
        
        jcbProyeccion.removeAll();
        ProyeccionData proyD = new ProyeccionData();
        
        for (Proyeccion p: proyD.listarProyecciones()) {
            
            if (!p.isEstado() == false) {
                
                jcbProyeccion.addItem(p);
            }
        }
    }
    
    private void cargarCombosS(){
        jcbSalas.removeAllItems();
        SalaData salaD = new SalaData ();
                
        for (Sala s: salaD.listarSala()) {
            
            if (!s.getEstado().equalsIgnoreCase("Inhabilitado")) {
                
                jcbSalas.addItem(s);

            }
        }
    }
    
    private void cargarFilas (){
        
        jcbFilas.removeAllItems();
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        
        AsientoData asientoD = new AsientoData();
        
        List<String> filas = asientoD.obtenerFilas(salaS.getIdSala());
        
        for (String fila : filas){
            
            jcbFilas.addItem(fila);
        }   
    }
    
      private void cargarNumerosPorFilas (){
        
        
        jcbNumero.removeAllItems();
        
        String fila = (String) jcbFilas.getSelectedItem();
        
        Sala salaS = (Sala) jcbSalas.getSelectedItem();
        
        AsientoData asientoD = new AsientoData();
        
        List <String> numeros = asientoD.obtenerNumeros(fila, salaS.getIdSala());
        
        for (String num : numeros) {
            
            jcbNumero.addItem(num);
        }         
    }
    
    private void limpiar(){
        
        jcbProyeccion.setSelectedIndex(-1);
        jcbSalas.setSelectedIndex(-1);
        jcbFilas.setSelectedIndex(-1);
        jcbNumero.setSelectedIndex(-1);
    }
    private void cabecera(){
        
        modelo.addColumn("ID Proyeccion");
        modelo.addColumn("Nro Sala");
        modelo.addColumn("Fila");
        modelo.addColumn("Numero");
        modelo.addColumn("Estado");
        
        jtAsientos.setModel(modelo);
    }
    
    private void configurarColores (){
        
        jtAsientos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            
            @Override
        
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
                    
                    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    
                    String estado = table.getValueAt(row, 4).toString();
                    
                    if (estado.equalsIgnoreCase("Disponible")) {
                        c.setBackground(new Color(144, 238, 144));                   
                    
                    } else {
                        
                        if (estado.equalsIgnoreCase("Ocupado")) {
                            
                            c.setBackground(new Color(255, 102, 102));
                        } else {
                            
                            c.setBackground(Color.WHITE);
                        }
                    }
                    
                    if (isSelected) {
                    
                        c.setBackground(new Color (135, 206, 250));
                    }
                
            
            return c;
                }
        });
    }
}
