/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import javax.swing.table.DefaultTableModel;
import Persistencia.*;
import Entidades.*;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
 

/**
 *
 * @author lucio
 */
public class CompradorV extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo= new DefaultTableModel();

    CompradorData compraD = new CompradorData();


    /**
     * Creates new form Comprador
     */
    public CompradorV() {
        initComponents();
        cabecera();      
        cargarMedios();
        this.setLocation(300, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtDni3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jcbMedioP = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jtEliminar = new javax.swing.JButton();
        jtModificar = new javax.swing.JButton();
        jbMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtComprador = new javax.swing.JTable();
        jbBuscar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jpContraseña = new javax.swing.JPasswordField();
        jpContraseña2 = new javax.swing.JPasswordField();
        jcMostrar = new javax.swing.JCheckBox();
        jcMostrar2 = new javax.swing.JCheckBox();
        jdtFechaN = new com.toedter.calendar.JDateChooser();

        jtDni3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDni3ActionPerformed(evt);
            }
        });

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comprador");

        jLabel2.setText("DNI:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Fecha de Nacimiento:");

        jLabel5.setText("Contraseña:");

        jLabel7.setText("Ingrese nuevamente la Contraseña:");

        jLabel8.setText("Medio de Pago:");

        jtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDniActionPerformed(evt);
            }
        });

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtEliminar.setText("Eliminar");
        jtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEliminarActionPerformed(evt);
            }
        });

        jtModificar.setText("Modificar");
        jtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtModificarActionPerformed(evt);
            }
        });

        jbMostrar.setText("Mostrar");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jtComprador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtComprador);

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jpContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpContraseñaActionPerformed(evt);
            }
        });

        jpContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpContraseña2ActionPerformed(evt);
            }
        });

        jcMostrar.setText("Mostrar");
        jcMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMostrarActionPerformed(evt);
            }
        });

        jcMostrar2.setText("Mostrar");
        jcMostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMostrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(jtModificar)
                                .addGap(42, 42, 42)
                                .addComponent(jtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcbMedioP, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jpContraseña2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jpContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                        .addComponent(jdtFechaN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtDni, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcMostrar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jcMostrar2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(12, 12, 12)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(301, 301, 301))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jdtFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jpContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcMostrar))
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jpContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcMostrar2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbMedioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jtEliminar)
                    .addComponent(jtModificar)
                    .addComponent(jbBuscar))
                .addGap(18, 18, 18)
                .addComponent(jbMostrar)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDniActionPerformed

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jtDni3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDni3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDni3ActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose ();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jpContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpContraseñaActionPerformed
        // TODO add your handling code here:
        jpContraseña.setEchoChar('*');
    }//GEN-LAST:event_jpContraseñaActionPerformed

    private void jpContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpContraseña2ActionPerformed
        // TODO add your handling code here:
        jpContraseña.setEchoChar('*');

    }//GEN-LAST:event_jpContraseña2ActionPerformed

    private void jcMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMostrarActionPerformed
        // TODO add your handling code here:
        if (jcMostrar.isSelected()){
            
            jpContraseña.setEchoChar((char) 0);
        } else {
            
            jpContraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_jcMostrarActionPerformed

    private void jcMostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMostrar2ActionPerformed
        // TODO add your handling code here:
        if (jcMostrar2.isSelected()){
            
            jpContraseña2.setEchoChar((char) 0);
        } else {
            
            jpContraseña2.setEchoChar('*');
        }
    }//GEN-LAST:event_jcMostrar2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ingresarC ();
        limpiarCampos ();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        // TODO add your handling code here:
        mostrarC();
    }//GEN-LAST:event_jbMostrarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:

        
        String id = jtDni.getText();
         
         if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Dni de la Persona que desee Buscar.");
        } else {
             
            buscarC();
            limpiarCampos();
         }  
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEliminarActionPerformed
        // TODO add your handling code here:
        
        String id = jtDni.getText();
         
         if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Dni de la Persona que desee borrar.");
        } else {
             
            eliminarC();
            limpiarCampos();
         }  
         
         mostrarC();
    }//GEN-LAST:event_jtEliminarActionPerformed

    private void jtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtModificarActionPerformed
        // TODO add your handling code here:
        String id = jtDni.getText();
         
        if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Dni de la Persona que desee borrar.");
        } else {
             
            modificarC();
            limpiarCampos();
        }   
         mostrarC();
    }//GEN-LAST:event_jtModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcMostrar;
    private javax.swing.JCheckBox jcMostrar2;
    private javax.swing.JComboBox<String> jcbMedioP;
    private com.toedter.calendar.JDateChooser jdtFechaN;
    private javax.swing.JPasswordField jpContraseña;
    private javax.swing.JPasswordField jpContraseña2;
    private javax.swing.JTable jtComprador;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtDni3;
    private javax.swing.JButton jtEliminar;
    private javax.swing.JButton jtModificar;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables

    private void ingresarC (){
        
        try{
            
            int dni = Integer.parseInt(jtDni.getText());
            
            String nombre = jtNombre.getText();
            
            Date fechaN = jdtFechaN.getDate();
            
            String clave = new String(jpContraseña.getPassword());
            String clave2 = new String(jpContraseña2.getPassword());
            
            
            
            String seleccion = (String) jcbMedioP.getSelectedItem();
            
            if (seleccion.equals("Seleccione una opcion")) {
                
                JOptionPane.showMessageDialog(this, "Debe eligir una forma de pago valido.");
                return;
            }
            
            if (clave.equalsIgnoreCase(clave2) && dni != 0 && nombre != null && fechaN != null && seleccion != "Seleccione una opcion" ) {
                
                Comprador comprador = new Comprador(dni, nombre, fechaN, clave, seleccion);
                
                compraD.guardarComprador(comprador);
            } else {
                
                JOptionPane.showMessageDialog(this, "Todos los campos son Obligatorios");
            }  
        }catch (NumberFormatException x ){
            
            JOptionPane.showMessageDialog(this, "Formato de Campos Incorrectos");
        }
    }
    
    private void buscarC(){
        
        modelo.setRowCount(0);

        try{
            
            int dni = Integer.parseInt(jtDni.getText());
            
            if (compraD.buscarComprador(dni) != null) {
                
                Comprador c = compraD.buscarComprador(dni);
                
                if (c != null) {
                    
                    modelo.addRow(new Object []{
                        
                        c.getDni(),
                        c.getNombre(),
                        c.getFechaNac(),
                        c.getPassword(),
                        c.getMedioPago()
                    });
                }
            }
            
        } catch (NumberFormatException x){
            
            JOptionPane.showMessageDialog(this, "Formato de Documento Incorrecto.");
        }
    }
    
    private void modificarC(){
        
        try{
            
            int dni = Integer.parseInt(jtDni.getText());
                        
            String nombre = jtNombre.getText();
            
            Date fechaN = jdtFechaN.getDate();
            
            String clave = new String(jpContraseña.getPassword());
            String clave2 = new String(jpContraseña2.getPassword());
            
            String seleccion = (String) jcbMedioP.getSelectedItem();
            
            String n = "";
            Date fN = null;
            String c = "";
            String c2 = "";
            
            String sele = "";
            
            Comprador compra = compraD.buscarComprador(dni);
            
            if (compra != null) {
                
                if (nombre.isEmpty()) {
                    
                    n = compra.getNombre();
                } else {
                    
                    n = nombre;
                }
                if (fechaN == null) {
                    
                    fN = compra.getFechaNac();
                } else {
                    
                    fN= fechaN;
                }
                if (clave.isEmpty() || clave2.isEmpty()) {
                    
                    c = compra.getPassword();
                    c2 = compra.getPassword();
                } else {
                    
                    if (clave.equalsIgnoreCase(clave2)) {
                        
                        c = clave;
                        c2 = clave2;
                    } else {
                        
                        JOptionPane.showMessageDialog(this, "Contraseña no Coinciden.");
                    }
                }
                
                if (seleccion == "Seleccione una opcion") {
                    
                    sele = compra.getMedioPago();
                } else {
                    
                    sele = seleccion;
                }
                
                Comprador comp = new Comprador(dni, n, fN, c, sele);
                
                int confirmar = JOptionPane.showConfirmDialog(this, "¿Estas seguro de eliminar el Comprador con el documento: " + jtDni.getText() + " ?"
                        , "Confirmar la Modificacion: ", JOptionPane.YES_NO_OPTION);
                if (confirmar == JOptionPane.YES_OPTION) {
                    
                    compraD.actualizarComprador(comp);
                }
            }        
        }catch (NumberFormatException x){
            
            JOptionPane.showMessageDialog(this, "Formato de DNI incorrecto.");
        }
        
    }
    
    private void eliminarC(){
        
        try{
            
            int dni = Integer.parseInt(jtDni.getText());
            
            if (compraD.buscarComprador(dni) != null) {
                
                int confirmar = JOptionPane.showConfirmDialog(this, "¿Estas seguro de eliminar el comprador con el documento: " + jtDni.getText() + "?",
                        "Confirmar el Borrado: ", JOptionPane.YES_NO_OPTION);
                
                if (confirmar == JOptionPane.YES_OPTION) {
                    
                    compraD.eliminarComprador(dni);
                }
            } else {
                
                JOptionPane.showMessageDialog(this, "No se encontro el DNI indicado");
            }
            
        }catch (NumberFormatException x){
            
            JOptionPane.showMessageDialog(this, "Formato de Documento Incorrecto");
            return;
        }
    }
    
    
    
    
    
    
    
    
    
    
    private void mostrarC(){
        
        modelo.setRowCount(0);
        List <Comprador> lista = compraD.listarCompradores();
        
        for (Comprador c: lista) {
            
            modelo.addRow(new Object []{
                c.getDni(),
                c.getNombre(),
                c.getFechaNac(),
                c.getPassword(),
                c.getMedioPago()
            });
        }
    }
    
    //---------- Vistas ----------
    
    private void cargarMedios (){
        
        jcbMedioP.addItem("Seleccione una opcion");
        jcbMedioP.addItem("Efectivo");
        jcbMedioP.addItem("Debito");
        jcbMedioP.addItem("Credito");
        jcbMedioP.addItem("Mercado Pago");
    }

    private void cabecera(){
        
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha de Nacimiento");
        modelo.addColumn("Password");
        modelo.addColumn("Medio Pago");
        
        jtComprador.setModel(modelo);
    }
    
    private void limpiarCampos (){
        
        jtDni.setText("");
        jtNombre.setText("");
        jdtFechaN.setDate(null);
        jpContraseña.setText("");
        jpContraseña2.setText("");
        jcbMedioP.setSelectedIndex(0);
        jcMostrar.setSelected(false);
        jcMostrar2.setSelected(false);
    }    
}
