/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author lucio
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        this.setLocationRelativeTo(null);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdEscritorio = new javax.swing.JDesktopPane();
        Fondo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPelicula = new javax.swing.JMenu();
        jmiPelicula = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiSalas = new javax.swing.JMenuItem();
        jmAsientos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdEscritorio.setBackground(new java.awt.Color(153, 153, 255));
        jdEscritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2140, Short.MAX_VALUE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1770, Short.MAX_VALUE)
        );

        jdEscritorio.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, 800));

        getContentPane().add(jdEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, 900));

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        jMenuBar1.setAlignmentY(0.47368422F);
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jMenuBar1.setName(""); // NOI18N

        jmPelicula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jmPelicula.setText("Peliculas");
        jmPelicula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jmiPelicula.setText("Pelicula");
        jmiPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPeliculaActionPerformed(evt);
            }
        });
        jmPelicula.add(jmiPelicula);

        jMenuBar1.add(jmPelicula);

        jMenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu2.setText("Salas");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jmiSalas.setText("Salas");
        jmiSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalasActionPerformed(evt);
            }
        });
        jMenu2.add(jmiSalas);

        jmAsientos.setText("Asientos");
        jmAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAsientosActionPerformed(evt);
            }
        });
        jMenu2.add(jmAsientos);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu3.setText("Proyeccion");
        jMenu3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jMenuItem1.setText("Proyecciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu4.setText("Comprador");
        jMenu4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenu4.setIconTextGap(8);

        jMenuItem2.setText("Usuario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu5.setText("Salir");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenu5.add(jmiSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
         int opcion; 
        
        opcion = JOptionPane.showConfirmDialog(this, "¿Desea Salir del programa?",
        "Confirmar salida", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            
            System.exit(0);  
        }
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalasActionPerformed
        // TODO add your handling code here:    
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        SalasV vistaS = new SalasV ();
        vistaS.setVisible(true);
        jdEscritorio.add(vistaS);
        jdEscritorio.moveToFront(vistaS);
    }//GEN-LAST:event_jmiSalasActionPerformed

    private void jmAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAsientosActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        AsientosV vistaA = new AsientosV ();
        vistaA.setVisible(true);
        jdEscritorio.add(vistaA);
        jdEscritorio.moveToFront(vistaA);

    }//GEN-LAST:event_jmAsientosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        ProyeccionesV vistaP = new ProyeccionesV ();
        vistaP.setVisible(true);
        jdEscritorio.add(vistaP);
        jdEscritorio.moveToFront(vistaP);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        CompradorV vistaC = new CompradorV ();
        vistaC.setVisible(true);
        jdEscritorio.add(vistaC);
        jdEscritorio.moveToFront(vistaC);        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmiPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPeliculaActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        PeliculasV vistaP = new PeliculasV ();
        vistaP.setVisible(true);
        jdEscritorio.add(vistaP);
        jdEscritorio.moveToFront(vistaP);
    }//GEN-LAST:event_jmiPeliculaActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane jdEscritorio;
    private javax.swing.JMenuItem jmAsientos;
    private javax.swing.JMenu jmPelicula;
    private javax.swing.JMenuItem jmiPelicula;
    private javax.swing.JMenuItem jmiSalas;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}