/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author lucio
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        this.setLocationRelativeTo(null);     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdEscritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmPelicula = new javax.swing.JMenu();
        jmiPelicula = new javax.swing.JMenuItem();
        jmSalas = new javax.swing.JMenu();
        jmiSala = new javax.swing.JMenuItem();
        jmiAsiento = new javax.swing.JMenuItem();
        jmProyeccion = new javax.swing.JMenu();
        jmiProyecciones = new javax.swing.JMenuItem();
        jmComprador = new javax.swing.JMenu();
        jmiUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdEscritorio.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jdEscritorioLayout = new javax.swing.GroupLayout(jdEscritorio);
        jdEscritorio.setLayout(jdEscritorioLayout);
        jdEscritorioLayout.setHorizontalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );
        jdEscritorioLayout.setVerticalGroup(
            jdEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jMenuBar2.setBackground(new java.awt.Color(153, 153, 255));
        jMenuBar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuBar2.setForeground(new java.awt.Color(153, 153, 255));

        jmPelicula.setText("Peliculas");

        jmiPelicula.setText("Pelicula");
        jmiPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPeliculaActionPerformed(evt);
            }
        });
        jmPelicula.add(jmiPelicula);

        jMenuBar2.add(jmPelicula);

        jmSalas.setText("Salas");
        jmSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalasActionPerformed(evt);
            }
        });

        jmiSala.setText("Sala");
        jmiSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalaActionPerformed(evt);
            }
        });
        jmSalas.add(jmiSala);

        jmiAsiento.setText("Asiento");
        jmiAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAsientoActionPerformed(evt);
            }
        });
        jmSalas.add(jmiAsiento);

        jMenuBar2.add(jmSalas);

        jmProyeccion.setText("Proyeccion");

        jmiProyecciones.setText("Proyecciones");
        jmiProyecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProyeccionesActionPerformed(evt);
            }
        });
        jmProyeccion.add(jmiProyecciones);

        jMenuBar2.add(jmProyeccion);

        jmComprador.setText("Comprador");

        jmiUsuario.setText("Usuario");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jmComprador.add(jmiUsuario);

        jMenuItem1.setText("Comprar Ticket");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmComprador.add(jMenuItem1);

        jMenuBar2.add(jmComprador);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalir);

        jMenuBar2.add(jmSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        CompradorV vistaC = new CompradorV ();
        vistaC.setVisible(true);
        jdEscritorio.add(vistaC);
        jdEscritorio.moveToFront(vistaC);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here: uups este no era lol
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
                   int opcion; 
        
        opcion = JOptionPane.showConfirmDialog(this, "¿Desea Salir del programa?",
        "Confirmar salida", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            
            System.exit(0);  
        }
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiProyeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProyeccionesActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        ProyeccionesV vistaP = new ProyeccionesV ();
        vistaP.setVisible(true);
        jdEscritorio.add(vistaP);
        jdEscritorio.moveToFront(vistaP);
    }//GEN-LAST:event_jmiProyeccionesActionPerformed

    private void jmSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalasActionPerformed
        // TODO add your handling code here: ooh este tampoco
    }//GEN-LAST:event_jmSalasActionPerformed

    private void jmiPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPeliculaActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        PeliculasV vistaP = new PeliculasV ();
        vistaP.setVisible(true);
        jdEscritorio.add(vistaP);
        jdEscritorio.moveToFront(vistaP);
    }//GEN-LAST:event_jmiPeliculaActionPerformed

    private void jmiSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalaActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        SalasV vistaS = new SalasV ();
        vistaS.setVisible(true);
        jdEscritorio.add(vistaS);
        jdEscritorio.moveToFront(vistaS);
    }//GEN-LAST:event_jmiSalaActionPerformed

    private void jmiAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAsientoActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        AsientosV vistaA = new AsientosV ();
        vistaA.setVisible(true);
        jdEscritorio.add(vistaA);
        jdEscritorio.moveToFront(vistaA);
    }//GEN-LAST:event_jmiAsientoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jdEscritorio.removeAll();
        jdEscritorio.repaint();
        TicketV vistaT = new TicketV ();
        vistaT.setVisible(true);
        jdEscritorio.add(vistaT);
        jdEscritorio.moveToFront(vistaT);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdEscritorio;
    private javax.swing.JMenu jmComprador;
    private javax.swing.JMenu jmPelicula;
    private javax.swing.JMenu jmProyeccion;
    private javax.swing.JMenu jmSalas;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAsiento;
    private javax.swing.JMenuItem jmiPelicula;
    private javax.swing.JMenuItem jmiProyecciones;
    private javax.swing.JMenuItem jmiSala;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiUsuario;
    // End of variables declaration//GEN-END:variables
}