/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.*;
import Persistencia.*;
import java.sql.*;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucio
 */
public class PeliculasV extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo= new DefaultTableModel();
    PeliculaData peliData = new PeliculaData();


    /**
     * Creates new form Peliculas
     */
    public PeliculasV() {
        initComponents();
        cabecera();
        this.setLocation(250, 10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPeliculas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jtDirector = new javax.swing.JTextField();
        jtActores = new javax.swing.JTextField();
        jtOrigen = new javax.swing.JTextField();
        jtGenero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtMostrar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jtBuscar = new javax.swing.JButton();
        jtModificar = new javax.swing.JButton();
        jtEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jtPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Director", "Actores", "Origen", "Genero", "Estreno", "En Cartelera"
            }
        ));
        jScrollPane1.setViewportView(jtPeliculas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peliculas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Titulo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Director:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Actores:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Origen:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Genero:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Estreno:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("ID:");

        jtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdActionPerformed(evt);
            }
        });

        jtMostrar.setText("Mostrar Peliculas");
        jtMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMostrarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jtBuscar.setText("Buscar");
        jtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarActionPerformed(evt);
            }
        });

        jtModificar.setText("Modificar");
        jtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtModificarActionPerformed(evt);
            }
        });

        jtEliminar.setText("Eliminar");
        jtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEliminarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbAlta.setText("Dar de Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setText("Dar de Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(50, 50, 50)
                                .addComponent(jtBuscar)
                                .addGap(50, 50, 50)
                                .addComponent(jtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jtEliminar)
                                .addGap(50, 50, 50)
                                .addComponent(jbAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(jbBaja))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtActores, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(jtGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                        .addGap(30, 30, 30)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtActores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jtBuscar)
                    .addComponent(jtModificar)
                    .addComponent(jtEliminar)
                    .addComponent(jbAlta)
                    .addComponent(jbBaja))
                .addGap(18, 34, Short.MAX_VALUE)
                .addComponent(jtMostrar)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdActionPerformed

    private void jtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarActionPerformed
        // TODO add your handling code here:
        
        String id = jtId.getText();
         
        jtId.setEditable(true);

         if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Id de la Pelicula que desee Buscar.");
        } else {
             
             buscarPelicula ();
             jtId.setEditable(false); 
             limpiarCampos();
         }          
    }//GEN-LAST:event_jtBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        
        jtId.setEditable(false);  

        ingrearPelicula ();
        limpiarCampos();
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEliminarActionPerformed
        // TODO add your handling code here:
        String id = jtId.getText();
         
        jtId.setEditable(true);

         if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Id de la Pelicula que desee Eliminar.");
        } else {
             
             eliminarPelis();
             jtId.setEditable(false);  
             limpiarCampos();
             cargarPeliculas();
         }                   
    }//GEN-LAST:event_jtEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        
        dispose ();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtModificarActionPerformed
        // TODO add your handling code here:
        String id = jtId.getText();
         
         jtId.setEditable(true);

         if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Id de la Pelicula que desee Modificar.");
        } else {
             
             modificar();
             jtId.setEditable(false);  
             limpiarCampos();
             cargarPeliculas();
         }          
    }//GEN-LAST:event_jtModificarActionPerformed

    private void jtMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMostrarActionPerformed
        // TODO add your handling code here:
        
        cargarPeliculas ();
    }//GEN-LAST:event_jtMostrarActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
        String id = jtId.getText();
         
         jtId.setEditable(true);

         if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Id de la Pelicula que desee Poner en Cartelera.");
        } else {
             
            darAlta();
            jtId.setEditable(false);  
            limpiarCampos();
            cargarPeliculas();
         }

    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
        String id = jtId.getText();
         
         jtId.setEditable(true);

         if (id.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Ingrese el Id de la Pelicula que desee Sacar de Cartelera.");
        } else {
             
            darBaja();
            jtId.setEditable(false);  
            limpiarCampos();
            cargarPeliculas();
         }
    }//GEN-LAST:event_jbBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtActores;
    private javax.swing.JButton jtBuscar;
    private javax.swing.JTextField jtDirector;
    private javax.swing.JButton jtEliminar;
    private javax.swing.JTextField jtGenero;
    private javax.swing.JTextField jtId;
    private javax.swing.JButton jtModificar;
    private javax.swing.JButton jtMostrar;
    private javax.swing.JTextField jtOrigen;
    private javax.swing.JTable jtPeliculas;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables

    private void ingrearPelicula () {

        boolean enCartelera = true;
        
        
        String titulo = jtTitulo.getText();
        String director = jtDirector.getText();
        String actores = jtActores.getText();
        String origen = jtOrigen.getText();
        String genero = jtGenero.getText();
        Date estreno = jdcEstreno.getDate();
                
        if (titulo.isEmpty() || director.isEmpty() || actores.isEmpty() || origen.isEmpty() || genero.isEmpty() || estreno == null) {
            
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
            return;
            
        } else {
            
            Pelicula peli = new Pelicula (0 ,titulo, director, actores, origen, genero, estreno, enCartelera);
            
            peliData.guardarPelicula(peli);
        }
    }
    private void buscarPelicula (){
        
        modelo.setRowCount(0);
        
        int id;
        String enCarte = "";
        
        try {
  
            id = Integer.parseInt(jtId.getText());
            
            if (peliData.buscarPelicula(id) != null) {
               
                Pelicula p = peliData.buscarPelicula(id);
              
                if (p.isEnCartelera() == true) {
                    
                    enCarte = "Si"; 
                }   else {
                
                    enCarte= "No";
                } 
            
                if (p != null) {
                
                    modelo.addRow(new Object []{
                    
                        p.getIdPelicula(),
                        p.getTitulo(),
                        p.getDirector(),
                        p.getActores(),
                        p.getOrigen(),
                        p.getOrigen(),
                        p.getGenero(),
                        p.getEstreno(),
                        enCarte
                    });
                }
            } else {
                
                JOptionPane.showMessageDialog(this, "No se encontro el ID indicado");
            }
        
        } catch (NumberFormatException e){
            
            JOptionPane.showMessageDialog(this, "El ID debe ser un numero entero.");
            return;
        }        
    }
    
    private void modificar(){
                
        int id;
   
        String titulo = jtTitulo.getText();
        String director = jtDirector.getText();
        String actores = jtActores.getText();
        String origen = jtOrigen.getText();
        String genero = jtGenero.getText();
        Date estreno = jdcEstreno.getDate();
        
        String tit = "";
        String dir = "";
        String acto = "Desconocido";
        String ori = "";
        String gen = "";
        Date estr = null;
                       
        boolean enCarte = true;
        try {
  
            id = Integer.parseInt(jtId.getText());
     
            Pelicula peli = peliData.buscarPelicula(id);
            
            if (peliData.buscarPelicula(id) != null) {
                 
                if (titulo.isEmpty() == true) {
            
                    tit = peli.getTitulo();
                } else {
            
                    tit = titulo;
                }
        
                if (director.isEmpty() == true) {
            
                    dir = peli.getDirector();
                } else {
            
                    dir = director;
                }
        
                if (actores.isEmpty() == true) {
            
                    acto = peli.getActores();
                } else {
            
                    acto = actores;
                }
        
                if (origen.isEmpty() == true) {
            
                    ori = peli.getOrigen();
                } else {
            
                    ori = origen;
                }
        
                if (genero.isEmpty() == true) {
            
                    gen = peli.getGenero();
                } else {
            
                    gen = genero;
                }
        
                if (estr == null) {
            
                    estr = peli.getEstreno();
                } else {
            
                    estr = estreno;
                }
        
                Pelicula peli2 = new Pelicula (id, tit, dir, acto, ori, gen, estr, enCarte);
        
                int confirmar = JOptionPane.showConfirmDialog(this, "¿Esta Seguro de Modificar la Pelicula: " + jtTitulo.getText() + "?" , 
                        " Confirmar Actualizacion:", JOptionPane.YES_NO_OPTION);
        
                if (confirmar == JOptionPane.YES_OPTION) {
                
                    peliData.modificarPelicula(peli2);           
                }
        
                } else {
                
                JOptionPane.showMessageDialog(this, "No se encontro el ID indicado.");
            }
            } catch (NumberFormatException e){
            
                JOptionPane.showMessageDialog(this, "El ID debe ser un numero entero.");
                return;
            }
        }
    
    private void eliminarPelis(){
        
        int id;
        
        try{
            
            id = Integer.parseInt(jtId.getText());
            
            if (peliData.buscarPelicula(id) != null) {
                
            
                int confirmar = JOptionPane.showConfirmDialog(this, "¿Esta Seguro de Eliminar la Pelicula:" + jtTitulo.getText() + "?", 
                        " Confirmar el Borrado: ", JOptionPane.YES_NO_OPTION);
            
                if (confirmar == JOptionPane.YES_OPTION) {
                
                    peliData.eliminarPelicula(id);
                }
            } else {
                
                JOptionPane.showMessageDialog(this, "No se encontro el ID indicado");
            }
        } catch (NumberFormatException e){
            
                JOptionPane.showMessageDialog(this, "El ID debe ser un numero entero.");
                return;
        }
    }
    
    private void darAlta(){
        
        int id;

        try{
            
            id = Integer.parseInt(jtId.getText());
            
            if (peliData.buscarPelicula(id) != null) {
                
                peliData.darDeAlta(id);
            } else {
                
                JOptionPane.showMessageDialog(this, "No se encontro el ID indicado");
            }
        } catch (NumberFormatException e){
            
            JOptionPane.showMessageDialog(this, "El ID debe ser un numero entero.");
            return;
        }  
    }
    
    private void darBaja (){
        
        int id;
        
        try {
            
            id = Integer.parseInt(jtId.getText());
            
            if (peliData.buscarPelicula(id) != null) {
                
                peliData.darDeBaja(id);
            } else {
                
                JOptionPane.showMessageDialog(this, "No se encontro el ID indicado");
            }
            
            
        } catch (NumberFormatException e){
            
            JOptionPane.showMessageDialog(this, "El Id debe ser un numero entero." );
        }
    }
    
    private void cargarPeliculas (){
            
        List <Pelicula> lista = peliData.listarPeliculas();
        modelo.setRowCount(0);
        String enCarte = "";
        

        for (Pelicula p: lista) {
            
            if (p.isEnCartelera() == true) {
                
                enCarte = "Si";
            
            }   else {
                
                enCarte= "No";
            }   
                
         
            modelo.addRow(new Object []{
               p.getIdPelicula(),
               p.getTitulo(),
               p.getDirector(),
               p.getActores(),
               p.getOrigen(),
               p.getGenero(),
               p.getEstreno(),
               enCarte
            });
        }

    }
  
    private void cabecera(){
        
        modelo.addColumn("ID");
        modelo.addColumn("Titulo");
        modelo.addColumn("Director");
        modelo.addColumn("Actores");
        modelo.addColumn("Origen");
        modelo.addColumn("Genero");
        modelo.addColumn("Estreno");
        modelo.addColumn("En Cartelera");
        
        jtPeliculas.setModel(modelo);
    }
    
     private void limpiarCampos(){
        
        jtId.setText("");
        jtTitulo.setText("");
        jtDirector.setText("");
        jtActores.setText("");
        jtOrigen.setText("");
        jtGenero.setText("");
        jdcEstreno.setDate(null);
    }
}
