/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.*;
import Persistencia.*;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucio
 */
public class TicketV extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel(){
        @Override
            public boolean isCellEditable(int row, int column){
                
                return false;
            }
    };
    
    AsientoData asientoD = new AsientoData();
    CompradorData compD = new CompradorData();
    TicketData tD = new TicketData();
    ProyeccionData proyD = new ProyeccionData();
    /**
     * Creates new form Ticket
     */
    public TicketV() {
        initComponents();

        cargarComboP();
        cargarComboC();
        limpiar();
        cabecera();

        this.setLocation(250, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTickets = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbComprador = new javax.swing.JComboBox<>();
        jcbProyeccion = new javax.swing.JComboBox<>();
        jcbFila = new javax.swing.JComboBox<>();
        jcbNumero = new javax.swing.JComboBox<>();
        jbComprar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbBuscarD = new javax.swing.JButton();
        jbMostrar = new javax.swing.JButton();
        jbBuscarP = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jcbSalas = new javax.swing.JComboBox<>();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Comprar Ticket");

        jtTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTickets);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Comprador:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Proyeccion:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sala:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fila:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Numero:");

        jcbProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProyeccionActionPerformed(evt);
            }
        });

        jcbFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFilaActionPerformed(evt);
            }
        });

        jbComprar.setText("Comprar Ticket");
        jbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Elimiar Ticket");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbBuscarD.setText("Buscar Por DNI");
        jbBuscarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarDActionPerformed(evt);
            }
        });

        jbMostrar.setText("Mostar Todos");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jbBuscarP.setText("Buscar Por Proy");
        jbBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarPActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jcbSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSalasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jcbComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jcbProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbFila, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jbComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbBuscarD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(153, 153, 153)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(162, 162, 162)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jbBuscarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jcbComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbProyeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jcbFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbComprar)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscarD)
                    .addComponent(jbMostrar)
                    .addComponent(jbBuscarP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jbSalir)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProyeccionActionPerformed
        // TODO add your handling code here:
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        if (proy != null) {
            
            cargarCombosS();
        }
    }//GEN-LAST:event_jcbProyeccionActionPerformed

    private void jcbFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFilaActionPerformed
        // TODO add your handling code here:
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        String fila = (String) jcbFila.getSelectedItem();
        
        if (proy == null) {
            
            return;
        } else {
            
            cargarNumero(fila);
        }
    }//GEN-LAST:event_jcbFilaActionPerformed

    private void jbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarActionPerformed
        // TODO add your handling code here:
        
       Proyeccion proyS= (Proyeccion) jcbProyeccion.getSelectedItem();
        
       Comprador comprS = (Comprador) jcbComprador.getSelectedItem();
        
       String fila = (String) jcbFila.getSelectedItem();
       String numeroStr = ((String) jcbNumero.getSelectedItem()).split(" ")[0];
        
        if (proyS == null || comprS == null || fila.isEmpty() || numeroStr.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Se debe Seleccionar todo los campos.");
        } else{
         comprarTicket();
         limpiar();
        }
    }//GEN-LAST:event_jbComprarActionPerformed

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_jbMostrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarDActionPerformed
        // TODO add your handling code here:
        
        Comprador comp = (Comprador) jcbComprador.getSelectedItem();
        
        if (comp == null) {
            
            JOptionPane.showMessageDialog(this, "Eliga un usuario para buscar sus tickets");
        } else {
            
            mostraTicketXDni();
            limpiar ();
        }
        
    }//GEN-LAST:event_jbBuscarDActionPerformed

    private void jbBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarPActionPerformed
        // TODO add your handling code here:
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        
        if (proy == null) {
            
            JOptionPane.showMessageDialog(this, "Eliga un usuario para buscar sus tickets");
        } else {
            
            mostrarTicketXProy();
            limpiar ();
        }
    }//GEN-LAST:event_jbBuscarPActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:        
        
            Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
            String fila = (String) jcbFila.getSelectedItem();
            borrarTicket();
            limpiar();
            cargarTabla();
            cargarFilas();
            cargarNumero(fila);
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        String fila = (String) jcbFila.getSelectedItem();
        String numeroStr = ((String) jcbNumero.getSelectedItem()).split(" ")[0];
        
        int filaTabla = jtTickets.getSelectedRow();
        
        if (filaTabla == -1) {
            
            JOptionPane.showMessageDialog(this, "Seleccione un ticket");
            return;
        } 
        
        if (proy == null || fila == "" || numeroStr.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Tiene que elegir Proyeccion, fila y numero. Para Modificar ");
            return;
        }
        
        modificarTicket();
        
        cargarTabla();
        cargarFilas();
        cargarNumero(fila);
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jcbSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSalasActionPerformed
        // TODO add your handling code here:
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        
        if (proy != null) {
            
            cargarFilas();
        }
        
    }//GEN-LAST:event_jcbSalasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscarD;
    private javax.swing.JButton jbBuscarP;
    private javax.swing.JButton jbComprar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Object> jcbComprador;
    private javax.swing.JComboBox<String> jcbFila;
    private javax.swing.JComboBox<String> jcbNumero;
    private javax.swing.JComboBox<Object> jcbProyeccion;
    private javax.swing.JComboBox<Object> jcbSalas;
    private javax.swing.JTable jtTickets;
    // End of variables declaration//GEN-END:variables

    private void comprarTicket(){
        
        Proyeccion proyS= (Proyeccion) jcbProyeccion.getSelectedItem();
        
        Comprador comprS = (Comprador) jcbComprador.getSelectedItem();
        
        String fila = (String) jcbFila.getSelectedItem();
       
        String numeroStr = ((String) jcbNumero.getSelectedItem()).split(" ")[0];
        int numero = Integer.parseInt(numeroStr);
        
        Asiento asiento = asientoD.buscarAsientoProy(proyS.getIdProyeccion(), fila, numero);
        
        if (asiento == null) {
            
            JOptionPane.showMessageDialog(this, "El asiento no existe para este proyecto.");
            return;
        }
        
        if (!asiento.isDisponible()) {
            
            JOptionPane.showMessageDialog(this, "Asiento ocupado en esta proyeccion.");
            return;
        }
            LocalDate fechaC = LocalDate.now();
       
            LocalDate fechaF = fechaC.plusDays(3);
                   
        
            double precio = proyS.getPrecioLugar();

            if (proyS.isEs3D() == true) {
            
                precio = precio + 2000;
                JOptionPane.showMessageDialog(this, "La Pelicula se le suman $2000 mas por ser en 3D");
            }
        
            if (proyS.isSubtitulada()) {
            
                precio = precio - 1000;
                JOptionPane.showMessageDialog(this, "La pelicula recibe un descuento de $1000 por estar Subtitulada");
            }
              
            Ticket ticket = new Ticket(0, fechaF, fechaC, precio, comprS, asiento);
            
            tD.generarTicket(ticket);
        
             asientoD.ocuparAsiento(asiento.getIdAsiento());

        
     }
    
    public void modificarTicket(){
        
        int filaTabla = jtTickets.getSelectedRow();
        
        if (filaTabla == -1) {
            
            JOptionPane.showMessageDialog(this, "Seleccione un ticket");
            return;
        }
        
        int idTicket = (int) modelo.getValueAt(filaTabla, 0);
        
        String nuevaFila = jcbFila.getSelectedItem().toString();
        String numeroStr = ((String) jcbNumero.getSelectedItem()).split(" ")[0];
        
        int nro = Integer.parseInt(numeroStr);
        
        tD.modificarFYN(idTicket, nuevaFila, nro);
    }
    
    private void borrarTicket(){
        
        int filaVista = jtTickets.getSelectedRow();
        
        if (filaVista == -1) {
            
            JOptionPane.showMessageDialog(this, "Seleccione un ticket.");
            return;
        }
        
        int filaModelo = jtTickets.convertRowIndexToModel(filaVista);
        
        int idTicket = (int) modelo.getValueAt(filaModelo, 0);
        
        tD.borrarTicket(idTicket);
        
    }
    
    public void mostraTicketXDni(){
        
        modelo.setRowCount(0);
        
        Comprador comprS = (Comprador) jcbComprador.getSelectedItem();
        
        int dni = comprS.getDni();
        
        List<Ticket> tickets = tD.buscarTicketsXComp(dni);
        
        for (Ticket t: tickets) {
            
            modelo.addRow(new Object []{
                
                t.getIdTicket() , 
                t.getComprador().getNombre() , 
                t.getFechaCompra() ,
                t.getPrecio() , 
                t.getAsientoComprado().getProy().getPelicula().getTitulo() ,
                t.getFechaFuncion() ,
                t.getAsientoComprado().getFila() ,
                t.getAsientoComprado().getNúmero()
            });
        }
    }
    
    public void mostrarTicketXProy(){
        modelo.setRowCount(0);
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        
        int idProy = proy.getIdProyeccion();
        
        for (Ticket t : tD.buscarTicketsXProy(idProy)) {
            modelo.addRow(new Object []{
                
                t.getIdTicket() , 
                t.getComprador().getNombre() , 
                t.getFechaCompra() ,
                t.getPrecio() , 
                t.getAsientoComprado().getProy().getPelicula().getTitulo() ,
                t.getFechaFuncion() , 
                t.getAsientoComprado().getFila() ,
                t.getAsientoComprado().getNúmero()
            });
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // -------------- Vista --------------
    
    private void cargarCombosS(){
        jcbSalas.removeAllItems();
        
        SalaData salaD = new SalaData ();
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
                
        if(proy == null){
            return;
        }
        
        Sala sala = proy.getSala();
        
        if (sala != null) {
            
            jcbSalas.addItem(proy.getSala());
        }
    }
    
    private void cargarComboP(){
        
        jcbProyeccion.removeAll();
        
        for (Proyeccion p: proyD.listarProyecciones()) {
            
            if (!p.isEstado() == false ) {
                
                jcbProyeccion.addItem(p);
            }
        }
    }
    
    private void cargarComboC(){
        
        jcbComprador.removeAll();
        
        for (Comprador c: compD.listarCompradores()) {
            
            jcbComprador.addItem(c);
        }
        
    }
    
    private void cargarFilas(){
        
        jcbFila.removeAllItems();
        jcbNumero.removeAllItems();
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        
        if (proy == null) {
            
            return;
        }
                
        List <String> filas = tD.obtenerFilas(proy.getIdProyeccion());
        
        for (String f: filas) {
            
            jcbFila.addItem(f);
        }
    }
    
    private void cargarNumero(String fila){
        
        jcbNumero.removeAllItems();
        
        Proyeccion proy = (Proyeccion) jcbProyeccion.getSelectedItem();
        
        List<String> numeros = tD.obtenerNumero(proy.getIdProyeccion(), fila);
        
        for (String num : numeros) {
            
            jcbNumero.addItem(num);
        }
    }
    
    private void limpiar(){
        
        jcbComprador.setSelectedIndex(-1);
        jcbProyeccion.setSelectedIndex(-1);
        jcbFila.setSelectedIndex(-1);
        jcbNumero.setSelectedIndex(-1);
        jcbSalas.setSelectedIndex(-1);
        
    }
    
    private void cabecera(){
        
        modelo.addColumn("Codigo Ticket");
        modelo.addColumn("Nombre");
        modelo.addColumn("Fecha de Compra");
        modelo.addColumn("Monto");
        modelo.addColumn("Pelicula");
        modelo.addColumn("Fecha Funcion");
        modelo.addColumn("Fila");
        modelo.addColumn("Numero");
        
        jtTickets.setModel(modelo);
    }
    
    private void cargarTabla(){
        
        modelo.setRowCount(0);
        
        for (Ticket t: tD.listarTickets()) {
            
            modelo.addRow(new Object []{
                t.getIdTicket() ,
                t.getComprador().getNombre() , 
                t.getFechaCompra() ,
                t.getPrecio() , 
                t.getAsientoComprado().getProy().getPelicula().getTitulo() ,
                t.getFechaFuncion(),
                t.getAsientoComprado().getFila(),
                t.getAsientoComprado().getNúmero()
            });
        }
    }
   

    


}
